version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - curl "https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip" -o packer.zip
      - unzip packer.zip -d packer
      - mv packer /usr/local/
      - export PATH="$PATH:/usr/local/packer"
  build:
    commands:
      - packer build images/$IMAGE/packer.json
