version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: docker
      env:
        variables:
          IMAGE: docker
    - identifier: nginx
      env:
        variables:
          IMAGE: nginx
    - identifier: nodejs
      env:
        variables:
          IMAGE: nodejs

phases:
  build:
    commands:
      - curl "https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip" -o packer.zip
      - unzip packer.zip -d packer
      - mv packer /usr/local/
      - export PATH="$PATH:/usr/local/packer"
      - packer build images/$IMAGE/packer.json
