version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
      - curl "https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip" -o packer.zip
      - unzip packer.zip -d packer
      - mv packer /usr/local/
      - export PATH="$PATH:/usr/local/packer"
  build:
    commands:
      - npm run build:images
