version: 0.2

phases:
  install:
    commands:
      - npm install
      - curl "https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip" -o packer.zip
      - unzip packer.zip -d packer
      - mv packer /usr/local/
      - export PATH="$PATH:/usr/local/packer"
  build:
    commands:
      - packer build images/docker/packer.json
      - packer build images/nginx/packer.json
      - packer build images/nodejs/packer.json
